@startuml
left to right direction

class Händler {
    - händlerNr: int
    - vorname: String
    - nachname: String
    - adresse: String
}

class Kunde {
    - kundenNr: int
    - vorname: String
    - nachname: String
    - rechnung: Rechnung[]
}

class Rechnung {
    - rechnungsNr: int
    - händlerNr: int
    - kundenNr: int
    - positionen: Rechnungsposition[]
}

class Produkt {
    - produktNr: int
    - teesorte: String
    - preis: double
}

class Rechnungsposition {
    - produktNr: int
    - anzahl: int
}

Kunde "1" -- "*" Rechnung
Händler "1" -- "*" Rechnung
Produkt "1" -- "1" Rechnungsposition
Rechnung "1" -- "*" Rechnungsposition


@enduml